### ISSUE TITLE
name 'model_name' is not defined

### ISSUE THREAD

**Issue by zhxieml** [Improbable-AI/curiosity_redteam#2]
Hi,

Congrats on the great work. I came across some issues with the llama2 script. Could you clarify what the 'model_name' refers to in this context?

https://github.com/Improbable-AI/curiosity_redteam/blob/da15590321fcd9780d882e3708a747fb06338d9e/ppo_gpt2_llama_safetyguard_peft_databrick_toxicity.py#L164

**Comment by williamd4112** [comment]
Thanks for pointing out this. I've fixed the script in the [new commit](https://github.com/Improbable-AI/curiosity_redteam/commit/88fcca099b5e5f67d4293b174a068220b427951b).

**Comment by williamd4112** [comment]
Fixed in the latest commit
