### ISSUE TITLE
Availability of Predicted Data

### ISSUE THREAD

**Issue by qtli** [Improbable-AI/curiosity_redteam#4]
Thanks for your exceptional work! I was wondering if you could provide the predicted data on Alpaca and Databricks datasets using the RL+Curiosity model. 
Thanks for your assistance in advance!

**Comment by williamd4112** [comment]
Hi @qtli 

Could you elaborate a bit about what "predicted data" is?

**Comment by qtli** [comment]
Thanks for your reply.
In section 4.4, we see that the red-team model can activate LLaMA2-7b-chat-hf, and Table 1 presents several examples. Since the paper discusses the curiosity-driven approach discovered 196 prompts that can elicit toxic responses, can you please provide the complete list of these prompts? Also, if possible, can you share any remaining prompts during the optimization that do not make LLaMA2-7b-chat-hf unsafe? Thanks again for your assistance. I aim to use this information for further exploration.

**Comment by williamd4112** [comment]
Hi @qtli  , I've sent those prompts to you via email since I'm not sure if those prompts are appropriate to be made public.
